type User @table(key: "uid") {
  uid: String! @default(expr: "auth.uid")
  displayName: String
}

type Room @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  environment: String! @default(value: "classroom")
  maxLimit: Int! @default(value: 5)
  host: User!
  createdAt: Timestamp! @default(expr: "request.time")
}

type RoomParticipant @table(key: ["room", "user"]) {
  room: Room!
  user: User!
  joinedAt: Timestamp! @default(expr: "request.time")
  activeDurationSeconds: Int! @default(value: 0)
}
